### PR TITLE
A multitude of changes ;)

### PR DESCRIPTION
**Pull request by brakf**
Hi guys,

I used your plugin for my mother in law's new shop but required some new features that were not included in your version. 
I figured: why not share those with you. There are no really groundbreaking changes, so I think you could like it.
The changes include:

- some small filters to add some more flexibility to hide the "pick up time" fields based on conditions.
- Possibility to configure multiple time ranges per day (e.g. if the shop is open in the morning and in the evening, but takes a break during noon time)
- above change required to calculate the settings array for the opening times dynamically. This additionally makes maintaining that part of the code much easier. However, it requires an adjustment of the translations (done for english and german).
- added a new page to the menu that provides an overview of orders for "today", "tomorrow", "next seven days". Here, also a total count of product quantities for those buckets is included. 
- added pickup time to the order preview in the admin dashboard. Looks like someone intended to do so earlier but simply left a method stub (I deleted that one).
- last but not least, adjusted the pot file & added german translation

I am quite new to wordpress + php development, so let me know where I can learn to do something better.

Fabian

### CODE REVIEW

**Comment by timnolte** [comment]
@brakf is the other PR that adds 3 filters a part of this PR? Can I close that one? If they aren't combined would you be able to combine them into this PR? I will review the PR this week.

**Comment by brakf** [comment]
Yes,will do. Need to check how to.

Tim Nolte <notifications@github.com> schrieb am Di., 11. Feb. 2020, 15:55:

**Comment by brakf** [comment]
closed the other one

**Comment by brakf** [comment]
Hi @timnolte ,

I did as you requested. However, I cannot adjust this PR anymore since you closed it. 
I think best would be to reopen this PR, and adjust the target of the merge to `dev-release/1.4.0`.

BR
Fabian

**Comment by timnolte** [comment]
@brakf just a heads up, can you please run the PHP linting and automatic fixes on your branch. Please make sure you are following all the WordPress and coding standards checked by PHP Code Sniffer. Thanks!

**Comment by brakf** [comment]
Hi Tim,
sorry, that it took me so long but I finally got back to this topic.
I ran a rebase of my branch to use the latest version of mattbanks:dev-release/1.4.0
I see now that that was probably not the wisest idea, but it looks like nothing broke ;)

I am still fighting to setup phpcs on my machine but will try to fix the standards issues asap and will then test everything once more to see if anything broke.

**Comment by brakf** [comment]
finally I was able to do the required formatting changes. 
(I miserably failed to get phpcs running in both atom and vscode. eventually I just used it from the command line)

regarding linting: I intentionally set phpcs:ignore on lines with WordPress.WP.I18n.NonSingularStringLiteralText
=> otherwise dynamic code would not be possible here

Also, I did a successful final functional test of my changes and am now hoping you like them to.

**Comment by timnolte** [comment]
@brakf so unfortunately, the key feature I am working on right now for version 1.4 is completely moving where the pickup time is stored. I'm not really keen on these huge PRs with so many different features all rolled in because if the sheer number of files that will end up changing. However, you are not the only one to have done this as I've had the same issue recently since I've spent a bunch of time to completely fix all of the source code issues using both PHP Code Sniffer as well as PHP static analysis using PHPStan. I also worked to refine the local development environment so that anyone wanting to contribute should be able to spin up an entire WordPress environment with everything needed to make changes and test those changes in a real setup. This also includes performing both code formatting and static analysis on commits so that you are unable to even commit and open a PR that won't pass the continuous integration builds.

Anyways, once I get this batch of changes made I will go through your PR and break it apart into smaller changes and provide each set to you so that you should be able to just create a branch lay down the code and submit the new PRs. I want to make sure you get the credit for the work but I want to be able to manage the changes in smaller chunks, most likely through multiple releases. I'm already planning on reducing the number of features I'm planning to roll out in each release in the hopes to make it easier for contributors as well as get features out faster.

Just a heads up that in regards to using phpcs:ignore statements I will only be accepting code changes with those under certain circumstances, and if they are included in a submission I will require code comments describing clearly why they were being used. For the ones you used it is actually not acceptable to use dynamic values for i18n.

**Comment by brakf** [comment]
Hi Tim,

thanks for the update. No worries about that!
If I understand correctly, I will just wait for you and then we will see if
my changes get added, correct?

BR
Fabian

Am Sa., 8. Aug. 2020 um 03:03 Uhr schrieb Tim Nolte <
notifications@github.com>:

**Comment by timnolte** [comment]
> Hi Tim,
> 
> thanks for the update. No worries about that!
> If I understand correctly, I will just wait for you and then we will see if
> my changes get added, correct?
> 
> BR
> Fabian

@brakf yes, nothing more you need to do at this point. Thanks!

**Pull request closed without merging**
